name: Development Build
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: |
        # cd mopo-web
        npm install

    - name: Deploy production
      if: github.event.ref == 'refs/heads/master'
      run: |
        cat ./Procfile
        
