name: Development Build
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: |
        # cd mopo-web
        npm install
  
    - name: List all file
      run: |
        ls .
      
    - name: Deploy production
      if: github.ref == 'refs/heads/master'
      run: |
        touch app2.js
        copy app.js app2.js
        git add -A
        git commit -m "changing "
        git push origin master
#       uses: canastro/copy-file-action@master
#       with:
#         source: "./app.js"
#         target: "./app2.js"

  
 
    - name: Development
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "DEv is"
        cat ./Procfile
        
      
        
